### ISSUE TITLE
Bot crashes if Botname is not changed on each restart

### ISSUE THREAD

**Issue by spacecheese** [Murgeye/teamspeak3-python-bot#7]
The bot will close and write the following to bot.log if the "Botname" in "config.ini" is not changed on every restart.
`2019-04-11 15:56:54,897: INFO: Started
2019-04-11 15:56:54,910: ERROR: Error on setting up client
Traceback (most recent call last):
  File "F:\Git\CJTF2TS3Bot\Bot.py", line 113, in setup_bot
    self.ts3conn.clientupdate(["client_nickname=" + self.bot_name])
  File "F:\Git\CJTF2TS3Bot\ts3\TS3Connection.py", line 290, in clientupdate
    self._send("clientupdate", params)
  File "F:\Git\CJTF2TS3Bot\ts3\TS3Connection.py", line 145, in _send
    decode(encoding='UTF-8').split("=", 1)[1])
ts3.TS3Connection.TS3QueryException: Query failed with id=513 msg=nickname is already in use`
This is due to Murgeye/teamspeak3-python-api#5

**Comment by Murgeye** [comment]
Both #6 and #7 should be fixed now, feel free to check!
